# Generated by Django 5.1 on 2024-11-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_teammember_created_at_alter_teammember_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
